export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  MENU_PRODUCTS: '/menu/products',
  STAFF: '/staff',
  REPORTS: '/reports',
  PROMOTIONS: '/promotions',
  CASHIER: '/cashier',
  CASHIER_PAYMENT: '/cashier/payment',
  CASHIER_FINANCE: '/cashier/finance',
  CASHIER_ADD_RECEIPT: '/cashier/finance/add-receipt',
  CASHIER_ADD_EXPENSE: '/cashier/finance/add-expense',
  WAITER: '/waiter',
  WAITER_RETURN: '/waiter/return',
  BARISTA: '/barista',
  BARISTA_INVENTORY: '/barista/inventory',
  BARISTA_IMPORT: '/barista/import',
  BARISTA_EXPORT: '/barista/export',
  BARISTA_STATS: '/barista/stats',
  ORDER: '/order',
  TABLES: '/tables',
} as const
